name: ekod_alumni
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
